<a href="https://colab.research.google.com/github/shindhuja2501/broadcasting/blob/master/broadcastingf25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
x=np.random.randint(20,size=(3,3))

In [3]:
x


array([[19,  8, 17],
       [10, 14,  1],
       [17, 17, 18]])

In [0]:
y=np.random.randint(20,size=(3,3))

In [5]:
y

array([[16,  5,  2],
       [14,  6,  4],
       [15, 13, 10]])

In [6]:
np.add(x,y)


array([[35, 13, 19],
       [24, 20,  5],
       [32, 30, 28]])

In [7]:
np.subtract(x,y)

array([[ 3,  3, 15],
       [-4,  8, -3],
       [ 2,  4,  8]])

In [8]:
np.abs(x,y)

array([[19,  8, 17],
       [10, 14,  1],
       [17, 17, 18]])

In [0]:
eigenvalues,eigenvectors=np.linalg.eig(x)

In [10]:
eigenvalues

array([40.52420075+0.j        ,  5.23789963+4.69478601j,
        5.23789963-4.69478601j])

In [11]:
eigenvectors

array([[ 0.65674407+0.j        , -0.64950756+0.j        ,
        -0.64950756-0.j        ],
       [ 0.27408859+0.j        ,  0.53587531+0.32505415j,
         0.53587531-0.32505415j],
       [ 0.70254015+0.j        ,  0.27362269-0.33233719j,
         0.27362269+0.33233719j]])

In [12]:
np.sort(x)


array([[ 8, 17, 19],
       [ 1, 10, 14],
       [17, 17, 18]])

In [13]:
np.argsort(y)

array([[1, 2, 0],
       [2, 0, 1],
       [0, 1, 2]])

In [0]:
i=np.array([1,2,3])

In [0]:
j=np.array([7,8,9])

In [16]:
i

array([1, 2, 3])

In [17]:
j

array([7, 8, 9])

In [0]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [19]:
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
l=np.array([7,7,7])

In [21]:
l

array([7, 7, 7])

In [22]:
np.add(k,l)

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [23]:
np.arange(5)+6

array([ 6,  7,  8,  9, 10])

In [24]:
k.shape

(3, 3)

In [25]:
k.ndim

2

In [26]:
k.nbytes

72

In [27]:
k.size

9

In [28]:
k.dtype

dtype('int64')

In [29]:
np.ones((3,3)).shape

(3, 3)

In [30]:
np.arange(3).shape

(3,)

In [31]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
np.ones((3,1))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [33]:
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.diagonal(k)

array([1, 5, 9])

In [35]:
np.diagonal(k,offset=1)

array([2, 6])

In [36]:
np.diagonal(k,offset=-1)

array([4, 8])

In [0]:
s=np.array([[2,1],[4,5]])

In [38]:
s

array([[2, 1],
       [4, 5]])

In [39]:
np.linalg.det(s)

6.0

In [40]:
k.trace()

15

In [41]:
k

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.linalg.inv(k)

LinAlgError: ignored

In [46]:
np.random.randint(100,size=(10))

array([85, 18, 21, 84, 59, 24, 86, 42, 18, 27])

In [47]:
x>3

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [48]:
x<3

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [49]:
x>=3

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [50]:
x<=3

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [51]:
x==3

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
x!=3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])