<a href="https://colab.research.google.com/github/shindhuja2501/broadcasting/blob/master/fancy%20indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
x=np.random.randint(20,size=(3,3))

In [3]:
x

array([[18,  6, 11],
       [ 1,  6,  7],
       [ 4,  3,  0]])

In [0]:
y=np.random.randint(20,size=(3,3))

In [5]:
y

array([[14,  4,  1],
       [ 3,  2,  9],
       [16, 14,  2]])

In [7]:
np.add(x,y)

array([[32, 10, 12],
       [ 4,  8, 16],
       [20, 17,  2]])

In [0]:
s=np.random.randint(25,size=(4,5))

In [9]:
s

array([[14, 10, 11, 10, 22],
       [16, 21,  8, 12, 21],
       [ 8,  5,  9, 11, 20],
       [15, 24, 16, 14, 24]])

In [10]:
s[0]

array([14, 10, 11, 10, 22])

In [11]:
s[1]

array([16, 21,  8, 12, 21])

In [12]:
s[2]

array([ 8,  5,  9, 11, 20])

In [13]:
s[3]

array([15, 24, 16, 14, 24])

In [14]:
s[1:,[1,2,3]]

array([[21,  8, 12],
       [ 5,  9, 11],
       [24, 16, 14]])

In [15]:
s[:2,[3,0,1]]

array([[10, 14, 10],
       [12, 16, 21]])

In [16]:
s


array([[14, 10, 11, 10, 22],
       [16, 21,  8, 12, 21],
       [ 8,  5,  9, 11, 20],
       [15, 24, 16, 14, 24]])

In [0]:
x=np.random.randint(50,size=(5,6))

In [19]:
x

array([[ 2, 31, 13, 35, 24, 28],
       [34, 41, 40, 14, 45, 38],
       [ 4,  1, 34, 31, 35, 47],
       [ 6, 23, 23, 14, 47, 19],
       [32, 32, 17,  6, 10, 45]])

In [20]:
x[0]


array([ 2, 31, 13, 35, 24, 28])

In [21]:
x[1]

array([34, 41, 40, 14, 45, 38])

In [22]:
x[2]

array([ 4,  1, 34, 31, 35, 47])

In [23]:
x[3]

array([ 6, 23, 23, 14, 47, 19])

In [24]:
x[4]

array([32, 32, 17,  6, 10, 45])

In [25]:
x

array([[ 2, 31, 13, 35, 24, 28],
       [34, 41, 40, 14, 45, 38],
       [ 4,  1, 34, 31, 35, 47],
       [ 6, 23, 23, 14, 47, 19],
       [32, 32, 17,  6, 10, 45]])

In [26]:
x[:,[4,2,0]]

array([[24, 13,  2],
       [45, 40, 34],
       [35, 34,  4],
       [47, 23,  6],
       [10, 17, 32]])

In [27]:
x[3:,[1,3,5]]


array([[23, 14, 19],
       [32,  6, 45]])

In [28]:
x[0:3,[0,2,4]]

array([[ 2, 13, 24],
       [34, 40, 45],
       [ 4, 34, 35]])

In [29]:
x[:,:]

array([[ 2, 31, 13, 35, 24, 28],
       [34, 41, 40, 14, 45, 38],
       [ 4,  1, 34, 31, 35, 47],
       [ 6, 23, 23, 14, 47, 19],
       [32, 32, 17,  6, 10, 45]])

In [30]:
x[:1,[3,4,5]]

array([[35, 24, 28]])

In [31]:
x[1:,[3,4,5]]

array([[14, 45, 38],
       [31, 35, 47],
       [14, 47, 19],
       [ 6, 10, 45]])

In [32]:
x[:3,[0,2,4]]

array([[ 2, 13, 24],
       [34, 40, 45],
       [ 4, 34, 35]])

In [0]:
a=np.random.randint(40,size=(6,6))

In [34]:
a

array([[35, 35, 25, 14, 22, 28],
       [10, 25, 10, 21,  3, 34],
       [22, 27, 13, 18, 21, 16],
       [39,  0, 30, 27, 18, 29],
       [10, 19, 21, 33, 13, 15],
       [33, 19, 26, 12, 27, 21]])

In [35]:
a[:3,[0,2,4]]

array([[35, 25, 22],
       [10, 10,  3],
       [22, 13, 21]])

In [36]:
a[:2,[1,3,5]]

array([[35, 14, 28],
       [25, 21, 34]])

In [0]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.diagonal(x)

array([1, 5, 9])

In [40]:
np.trace(x)

15

In [0]:
x=np.random.randint(100,size=(6,7))

In [42]:
x

array([[80, 25, 60, 75, 74, 39, 31],
       [65,  7, 35, 40,  5, 57, 30],
       [ 9, 16, 41, 99,  9, 26, 13],
       [28, 81, 68,  0, 70, 25, 47],
       [28, 25, 25, 71, 64, 57, 32],
       [25, 33, 45,  6, 67, 22, 60]])

In [43]:
x.T

array([[80, 65,  9, 28, 28, 25],
       [25,  7, 16, 81, 25, 33],
       [60, 35, 41, 68, 25, 45],
       [75, 40, 99,  0, 71,  6],
       [74,  5,  9, 70, 64, 67],
       [39, 57, 26, 25, 57, 22],
       [31, 30, 13, 47, 32, 60]])

In [44]:
x.diagonal(offset=1)

array([25, 35, 99, 70, 57, 60])

In [45]:
x.diagonal()


array([80,  7, 41,  0, 64, 22])

In [46]:
x.diagonal(offset=-1)

array([65, 16, 68, 71, 67])

In [47]:
x.diagonal(offset=2)

array([60, 40,  9, 25, 32])

In [0]:
s=np.random.randint(60,size=(5,5))

In [49]:
s

array([[28, 30, 13, 17, 28],
       [35,  6, 37, 25, 14],
       [33, 37, 45, 54, 15],
       [52, 26, 37, 59, 54],
       [50, 20, 10, 23, 46]])

In [50]:
np.sort(s)

array([[13, 17, 28, 28, 30],
       [ 6, 14, 25, 35, 37],
       [15, 33, 37, 45, 54],
       [26, 37, 52, 54, 59],
       [10, 20, 23, 46, 50]])

In [0]:
c=np.random.randint(50,size=(6,6))

In [52]:
c

array([[ 5, 21, 39,  7, 25, 44],
       [49, 22, 39,  6, 11, 49],
       [20, 15,  5, 35, 16, 13],
       [38, 42, 16, 43, 48, 10],
       [ 7, 24, 27, 13, 32, 11],
       [ 6, 11, 30, 19, 33, 22]])